name: ternav_icons
description: TernavIcons for your Flutter project.
version: 1.0.0
homepage: https://github.com/H3mnz/ternav_icons

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: TernavIconsBold
      fonts:
        - asset: fonts/TernavIconsBold.ttf
    - family: TernavIconsLight
      fonts:
        - asset: fonts/TernavIconsLight.ttf
    - family: TernavIconsLightOutline
      fonts:
        - asset: fonts/TernavIconsLightOutline.ttf
